name: triplet_repeat_automation
channels:
  - defaults
dependencies:
  - numpy=1.19.2
  - openpyxl=3.0.6
  - pandas=1.2.1
  - pip=20.3.3
  - pyinstaller=3.6
  - python=3.8.5
  - xlrd=2.0.1
  - pip:
    - xlwings==0.22.0

